import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Finance & Banking Careers Seed Data
 * 45 comprehensive finance career profiles covering 7 major career tracks
 *
 * CAREER PROGRESSION PATHS:
 *
 * Banking Track (7 careers):
 * Banking Intern → Bank Teller → Personal Banker → Relationship Manager →
 * Branch Manager → Regional Banking Manager → Head of Retail Banking
 *
 * Corporate Finance Track (7 careers):
 * Finance Intern → Junior Financial Analyst → Financial Analyst → Senior Financial Analyst →
 * Finance Manager → Finance Director → CFO
 *
 * Investment Banking Track (6 careers):
 * IB Intern → IB Analyst → IB Associate → VP (IB) → Director (IB) → Managing Director (IB)
 *
 * Accounting Track (8 careers):
 * Accounting Intern → Junior Accountant → Accountant → Senior Accountant →
 * Accounting Manager → Financial Controller → Finance Director (Accounting) → CAO
 *
 * Big 4 Track (6 careers):
 * Audit/Tax Intern → Associate → Senior Associate → Manager → Senior Manager → Partner
 *
 * FinTech Track (5 careers):
 * FinTech Intern → Junior FinTech Analyst → FinTech Product Manager →
 * Senior FinTech Strategist → Head of FinTech Innovation
 *
 * Financial Advisory/Consulting Track (6 careers):
 * Consulting Intern → Junior Consultant → Consultant → Senior Consultant → Manager → Director
 */

const financeCareers = [
  // ==========================================
  // PHASE 1: BANKING TRACK (7 careers)
  // ==========================================

  {
    name: 'Banking Intern',
    vietnameseName: 'Thực tập sinh Ngân hàng',
    description: 'Entry-level internship learning banking operations and customer service. Assists with account opening, document processing, customer inquiries, and branch administrative tasks. Perfect starting point for undergraduate students interested in retail or commercial banking careers.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 70,
        conscientiousness: 75,
        extraversion: 65,
        agreeableness: 80,
        neuroticism: 45,
        eq_emotional_intelligence: 65,
        adaptability: 75,
        stress_tolerance: 60,
      },
      a2: {
        analytical_thinking: 65,
        creativity: 50,
        technical_aptitude: 65,
        communication_written: 65,
        communication_verbal: 70,
        attention_to_detail: 80,
        time_management: 65,
        digital_literacy: 75,
        learning_agility: 85,
        quantitative_analysis: 65,
        financial_modeling: 40,
        risk_assessment: 45,
        regulatory_knowledge: 40,
        business_acumen: 50,
      },
      a3: {
        work_life_balance: 75,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 25,
        impact_vs_money: 40,
        stability_vs_growth: 70,
        collaboration_vs_solo: 75,
        variety_vs_routine: 55,
      },
    },
    avgSalaryVND: '2,000,000 - 5,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'low',
    growthPotential: 'very_high',
  },

  {
    name: 'Bank Teller',
    vietnameseName: 'Giao dịch viên Ngân hàng',
    description: 'Front-line customer service role handling daily banking transactions including deposits, withdrawals, money transfers, and account services. Provides excellent customer experience while maintaining accuracy and security in cash handling and account management.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 65,
        conscientiousness: 85,
        extraversion: 75,
        agreeableness: 85,
        neuroticism: 40,
        eq_emotional_intelligence: 75,
        adaptability: 70,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 65,
        creativity: 50,
        technical_aptitude: 70,
        communication_written: 65,
        communication_verbal: 80,
        attention_to_detail: 95,
        time_management: 75,
        digital_literacy: 75,
        learning_agility: 70,
        quantitative_analysis: 70,
        financial_modeling: 40,
        risk_assessment: 55,
        regulatory_knowledge: 60,
        business_acumen: 55,
      },
      a3: {
        work_life_balance: 70,
        creativity_vs_structure: 25,
        autonomy_vs_guidance: 35,
        impact_vs_money: 45,
        stability_vs_growth: 75,
        collaboration_vs_solo: 80,
        variety_vs_routine: 50,
      },
    },
    avgSalaryVND: '4,700,000 - 5,600,000',
    workHoursPerWeek: 42,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Personal Banker',
    vietnameseName: 'Chuyên viên Ngân hàng Cá nhân',
    description: 'Sales-focused role building relationships with retail customers and selling banking products including savings accounts, credit cards, personal loans, and insurance. Meets sales targets while providing financial advice and solutions tailored to customer needs.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 70,
        conscientiousness: 80,
        extraversion: 85,
        agreeableness: 80,
        neuroticism: 35,
        eq_emotional_intelligence: 85,
        adaptability: 75,
        stress_tolerance: 70,
      },
      a2: {
        analytical_thinking: 70,
        creativity: 60,
        technical_aptitude: 70,
        communication_written: 70,
        communication_verbal: 90,
        attention_to_detail: 80,
        time_management: 75,
        digital_literacy: 75,
        learning_agility: 75,
        quantitative_analysis: 75,
        financial_modeling: 50,
        risk_assessment: 65,
        regulatory_knowledge: 65,
        business_acumen: 70,
      },
      a3: {
        work_life_balance: 60,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 50,
        impact_vs_money: 35,
        stability_vs_growth: 65,
        collaboration_vs_solo: 75,
        variety_vs_routine: 65,
      },
    },
    avgSalaryVND: '8,000,000 - 12,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Relationship Manager',
    vietnameseName: 'Quản lý Quan hệ Khách hàng',
    description: 'Manages portfolio of high-value individual or corporate clients, providing comprehensive banking solutions and financial advisory services. Develops long-term client relationships, cross-sells banking products, and achieves revenue targets through personalized service.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 85,
        extraversion: 90,
        agreeableness: 80,
        neuroticism: 30,
        eq_emotional_intelligence: 90,
        adaptability: 80,
        stress_tolerance: 75,
        leadership: 70,
      },
      a2: {
        analytical_thinking: 80,
        creativity: 65,
        technical_aptitude: 75,
        communication_written: 80,
        communication_verbal: 95,
        attention_to_detail: 80,
        time_management: 80,
        digital_literacy: 80,
        learning_agility: 75,
        quantitative_analysis: 80,
        financial_modeling: 65,
        risk_assessment: 75,
        regulatory_knowledge: 70,
        business_acumen: 80,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 65,
        impact_vs_money: 30,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '4,300,000 - 12,200,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'very_high',
  },

  {
    name: 'Branch Manager',
    vietnameseName: 'Giám đốc Chi nhánh Ngân hàng',
    description: 'Leads all operations of bank branch including sales, customer service, risk management, and staff supervision. Responsible for branch profitability, regulatory compliance, business development, and team management of 10-30 employees.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 90,
        extraversion: 85,
        agreeableness: 75,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 80,
        stress_tolerance: 85,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 65,
        technical_aptitude: 75,
        communication_written: 80,
        communication_verbal: 90,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 75,
        learning_agility: 70,
        quantitative_analysis: 85,
        financial_modeling: 70,
        risk_assessment: 85,
        regulatory_knowledge: 85,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 80,
        impact_vs_money: 40,
        stability_vs_growth: 65,
        collaboration_vs_solo: 75,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '15,600,000 - 30,600,000',
    workHoursPerWeek: 50,
    stressLevel: 'very_high',
    growthPotential: 'high',
  },

  {
    name: 'Regional Banking Manager',
    vietnameseName: 'Giám đốc Ngân hàng Khu vực',
    description: 'Oversees multiple bank branches across a geographic region, managing branch managers, setting regional strategy, and driving business growth. Responsible for multi-branch performance, regional P&L, talent development, and market expansion.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 85,
        agreeableness: 70,
        neuroticism: 20,
        eq_emotional_intelligence: 95,
        adaptability: 85,
        stress_tolerance: 90,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 70,
        technical_aptitude: 75,
        communication_written: 85,
        communication_verbal: 95,
        attention_to_detail: 80,
        time_management: 90,
        digital_literacy: 75,
        learning_agility: 70,
        quantitative_analysis: 90,
        financial_modeling: 75,
        risk_assessment: 90,
        regulatory_knowledge: 90,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 90,
        impact_vs_money: 45,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '50,000,000 - 80,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Head of Retail Banking',
    vietnameseName: 'Giám đốc Ngân hàng Bán lẻ',
    description: 'C-suite executive leading entire retail banking division nationwide. Sets strategic direction, manages regional managers, oversees billions in deposits and loans, drives digital transformation, and ensures profitability and growth of retail banking operations.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 85,
        agreeableness: 70,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 85,
        stress_tolerance: 95,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 75,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 80,
        time_management: 90,
        digital_literacy: 80,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 80,
        risk_assessment: 95,
        regulatory_knowledge: 95,
        business_acumen: 98,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 95,
        impact_vs_money: 50,
        stability_vs_growth: 55,
        collaboration_vs_solo: 65,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '80,000,000 - 120,000,000',
    workHoursPerWeek: 60,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ==========================================
  // PHASE 2: CORPORATE FINANCE TRACK (7 careers)
  // ==========================================

  {
    name: 'Finance Intern',
    vietnameseName: 'Thực tập sinh Tài chính',
    description: 'Entry-level internship learning corporate finance fundamentals. Assists finance team with data entry, financial analysis, report preparation, and budget tracking. Gains exposure to financial planning, accounting, and business operations.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 80,
        extraversion: 55,
        agreeableness: 75,
        neuroticism: 45,
        eq_emotional_intelligence: 65,
        adaptability: 80,
        stress_tolerance: 60,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 55,
        technical_aptitude: 75,
        communication_written: 70,
        communication_verbal: 65,
        attention_to_detail: 85,
        time_management: 70,
        digital_literacy: 80,
        learning_agility: 90,
        quantitative_analysis: 80,
        financial_modeling: 50,
        risk_assessment: 50,
        regulatory_knowledge: 45,
        business_acumen: 55,
      },
      a3: {
        work_life_balance: 70,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 25,
        impact_vs_money: 45,
        stability_vs_growth: 75,
        collaboration_vs_solo: 70,
        variety_vs_routine: 60,
      },
    },
    avgSalaryVND: '2,000,000 - 6,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'low',
    growthPotential: 'very_high',
  },

  {
    name: 'Junior Financial Analyst',
    vietnameseName: 'Chuyên viên Phân tích Tài chính Cơ sở',
    description: 'Entry-level analyst supporting financial planning and analysis (FP&A) activities. Creates financial reports, maintains budgets, analyzes variances, builds Excel models, and assists senior analysts with forecasting and strategic projects.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 70,
        conscientiousness: 85,
        extraversion: 50,
        agreeableness: 70,
        neuroticism: 40,
        eq_emotional_intelligence: 65,
        adaptability: 75,
        stress_tolerance: 70,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 60,
        technical_aptitude: 85,
        communication_written: 75,
        communication_verbal: 70,
        attention_to_detail: 90,
        time_management: 75,
        digital_literacy: 85,
        learning_agility: 85,
        quantitative_analysis: 90,
        financial_modeling: 75,
        risk_assessment: 60,
        regulatory_knowledge: 55,
        business_acumen: 65,
      },
      a3: {
        work_life_balance: 65,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 40,
        impact_vs_money: 45,
        stability_vs_growth: 70,
        collaboration_vs_solo: 60,
        variety_vs_routine: 55,
      },
    },
    avgSalaryVND: '10,000,000 - 18,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'Financial Analyst',
    vietnameseName: 'Chuyên viên Phân tích Tài chính',
    description: 'Analyzes financial data to support business decisions. Prepares monthly/quarterly reports, builds financial models, conducts variance analysis, supports budgeting and forecasting, and provides insights to management on financial performance and opportunities.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 90,
        extraversion: 55,
        agreeableness: 70,
        neuroticism: 35,
        eq_emotional_intelligence: 70,
        adaptability: 75,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 65,
        technical_aptitude: 90,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 95,
        time_management: 80,
        digital_literacy: 90,
        learning_agility: 80,
        quantitative_analysis: 95,
        financial_modeling: 85,
        risk_assessment: 70,
        regulatory_knowledge: 65,
        business_acumen: 75,
      },
      a3: {
        work_life_balance: 60,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 55,
        impact_vs_money: 50,
        stability_vs_growth: 65,
        collaboration_vs_solo: 55,
        variety_vs_routine: 60,
      },
    },
    avgSalaryVND: '18,000,000 - 30,000,000',
    workHoursPerWeek: 47,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'Senior Financial Analyst',
    vietnameseName: 'Chuyên viên Phân tích Tài chính Cấp cao',
    description: 'Leads complex financial analysis projects and strategic initiatives. Develops sophisticated financial models, conducts business case analysis, presents to senior management, mentors junior analysts, and drives financial planning processes for business units.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 90,
        extraversion: 60,
        agreeableness: 70,
        neuroticism: 30,
        eq_emotional_intelligence: 75,
        adaptability: 80,
        stress_tolerance: 80,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 70,
        technical_aptitude: 90,
        communication_written: 85,
        communication_verbal: 80,
        attention_to_detail: 95,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 75,
        quantitative_analysis: 95,
        financial_modeling: 95,
        risk_assessment: 80,
        regulatory_knowledge: 70,
        business_acumen: 85,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 70,
        impact_vs_money: 55,
        stability_vs_growth: 60,
        collaboration_vs_solo: 60,
        variety_vs_routine: 65,
      },
    },
    avgSalaryVND: '30,000,000 - 55,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Finance Manager',
    vietnameseName: 'Quản lý Tài chính',
    description: 'Manages finance team and oversees financial planning, analysis, and reporting for business unit or department. Leads budgeting cycles, financial reviews, presents to executives, develops team capabilities, and ensures accuracy and timeliness of financial deliverables.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 70,
        agreeableness: 75,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 80,
        stress_tolerance: 85,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 70,
        technical_aptitude: 85,
        communication_written: 85,
        communication_verbal: 85,
        attention_to_detail: 90,
        time_management: 90,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 90,
        risk_assessment: 85,
        regulatory_knowledge: 80,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 80,
        impact_vs_money: 55,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 65,
      },
    },
    avgSalaryVND: '50,000,000 - 85,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Finance Director',
    vietnameseName: 'Giám đốc Tài chính',
    description: 'Senior finance leader overseeing finance function for major business division or medium-sized company. Develops financial strategy, manages large teams, drives business partnering, presents to C-suite and board, and ensures financial integrity and performance.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 70,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 90,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 85,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 85,
        time_management: 90,
        digital_literacy: 80,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 85,
        risk_assessment: 90,
        regulatory_knowledge: 90,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 90,
        impact_vs_money: 60,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '80,000,000 - 140,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Chief Financial Officer (CFO)',
    vietnameseName: 'Giám đốc Tài chính (CFO)',
    description: 'Top financial executive responsible for all financial operations, strategy, and reporting. C-suite member overseeing accounting, FP&A, treasury, tax, and risk. Ensures financial health, capital allocation, investor relations, regulatory compliance, and supports CEO in driving company strategy.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 98,
        extraversion: 80,
        agreeableness: 70,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 85,
        stress_tolerance: 95,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 75,
        technical_aptitude: 85,
        communication_written: 95,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 95,
        digital_literacy: 80,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 85,
        risk_assessment: 95,
        regulatory_knowledge: 95,
        business_acumen: 98,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 98,
        impact_vs_money: 65,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '120,000,000 - 250,000,000',
    workHoursPerWeek: 60,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ==========================================
  // PHASE 3: INVESTMENT BANKING TRACK (6 careers)
  // ==========================================

  {
    name: 'Investment Banking Intern',
    vietnameseName: 'Thực tập sinh Ngân hàng Đầu tư',
    description: 'Competitive internship at investment banks learning M&A, capital raising, and financial advisory. Builds financial models, prepares pitchbooks, conducts company research, and supports deal teams with analysis and presentations. Extremely demanding but prestigious entry point.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 90,
        extraversion: 65,
        agreeableness: 65,
        neuroticism: 40,
        eq_emotional_intelligence: 70,
        adaptability: 85,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 65,
        technical_aptitude: 90,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 95,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 95,
        quantitative_analysis: 95,
        financial_modeling: 75,
        risk_assessment: 65,
        regulatory_knowledge: 55,
        business_acumen: 70,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 30,
        impact_vs_money: 25,
        stability_vs_growth: 70,
        collaboration_vs_solo: 60,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '3,000,000 - 7,000,000',
    workHoursPerWeek: 60,
    stressLevel: 'very_high',
    growthPotential: 'very_high',
  },

  {
    name: 'Investment Banking Analyst',
    vietnameseName: 'Chuyên viên Phân tích Ngân hàng Đầu tư',
    description: 'Entry-level IB professional working on M&A deals, IPOs, and capital raising transactions. Creates complex financial models (DCF, LBO, M&A), builds pitch materials, conducts due diligence, and works 60-80 hour weeks. High-intensity role with steep learning curve and excellent exit opportunities.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 65,
        agreeableness: 60,
        neuroticism: 35,
        eq_emotional_intelligence: 70,
        adaptability: 85,
        stress_tolerance: 90,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 70,
        technical_aptitude: 95,
        communication_written: 85,
        communication_verbal: 75,
        attention_to_detail: 98,
        time_management: 90,
        digital_literacy: 95,
        learning_agility: 90,
        quantitative_analysis: 98,
        financial_modeling: 95,
        risk_assessment: 75,
        regulatory_knowledge: 65,
        business_acumen: 80,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 40,
        impact_vs_money: 20,
        stability_vs_growth: 60,
        collaboration_vs_solo: 55,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '8,000,000 - 24,000,000',
    workHoursPerWeek: 70,
    stressLevel: 'very_high',
    growthPotential: 'very_high',
  },

  {
    name: 'Investment Banking Associate',
    vietnameseName: 'Chuyên gia Ngân hàng Đầu tư',
    description: 'Mid-level IB role managing analysts and taking on more client-facing responsibilities. Leads financial modeling, coordinates due diligence, manages deal processes, participates in client meetings, and mentors analysts. Promoted from analyst or lateral hire with MBA.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 65,
        neuroticism: 30,
        eq_emotional_intelligence: 80,
        adaptability: 85,
        stress_tolerance: 95,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 95,
        communication_written: 90,
        communication_verbal: 85,
        attention_to_detail: 95,
        time_management: 90,
        digital_literacy: 90,
        learning_agility: 80,
        quantitative_analysis: 98,
        financial_modeling: 98,
        risk_assessment: 85,
        regulatory_knowledge: 75,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 60,
        impact_vs_money: 25,
        stability_vs_growth: 55,
        collaboration_vs_solo: 60,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '25,000,000 - 45,000,000',
    workHoursPerWeek: 70,
    stressLevel: 'very_high',
    growthPotential: 'very_high',
  },

  {
    name: 'Vice President (Investment Banking)',
    vietnameseName: 'Phó Giám đốc Ngân hàng Đầu tư',
    description: 'Senior banker managing deal execution and client relationships. Leads transaction teams, coordinates with senior bankers, manages multiple deals simultaneously, develops junior talent, and builds client pipeline. Bridge between execution and origination.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 85,
        agreeableness: 65,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 95,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 80,
        technical_aptitude: 90,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 90,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 75,
        quantitative_analysis: 95,
        financial_modeling: 95,
        risk_assessment: 90,
        regulatory_knowledge: 85,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 75,
        impact_vs_money: 30,
        stability_vs_growth: 50,
        collaboration_vs_solo: 65,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '40,000,000 - 75,000,000',
    workHoursPerWeek: 65,
    stressLevel: 'very_high',
    growthPotential: 'high',
  },

  {
    name: 'Director (Investment Banking)',
    vietnameseName: 'Giám đốc Ngân hàng Đầu tư',
    description: 'Senior investment banker focused on deal origination and client coverage. Develops and maintains C-suite relationships, sources new transactions, leads pitch processes, oversees deal teams, and drives revenue generation for the bank.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 90,
        agreeableness: 65,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 95,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 85,
        technical_aptitude: 85,
        communication_written: 95,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 95,
        digital_literacy: 80,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 90,
        risk_assessment: 95,
        regulatory_knowledge: 90,
        business_acumen: 98,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 85,
        impact_vs_money: 30,
        stability_vs_growth: 50,
        collaboration_vs_solo: 60,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '70,000,000 - 120,000,000',
    workHoursPerWeek: 65,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Managing Director (Investment Banking)',
    vietnameseName: 'Giám đốc Điều hành Ngân hàng Đầu tư',
    description: 'Top-tier investment banker and senior relationship manager. Owns client relationships with major corporations, leads major M&A transactions and capital raises, drives firm strategy, manages P&L, and represents bank at highest levels. Compensation heavily tied to deal performance.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 95,
        agreeableness: 65,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 85,
        stress_tolerance: 98,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 85,
        technical_aptitude: 80,
        communication_written: 95,
        communication_verbal: 100,
        attention_to_detail: 80,
        time_management: 95,
        digital_literacy: 75,
        learning_agility: 70,
        quantitative_analysis: 90,
        financial_modeling: 85,
        risk_assessment: 95,
        regulatory_knowledge: 95,
        business_acumen: 100,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 95,
        impact_vs_money: 25,
        stability_vs_growth: 45,
        collaboration_vs_solo: 60,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '100,000,000 - 200,000,000',
    workHoursPerWeek: 65,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ==========================================
  // PHASE 4: ACCOUNTING TRACK (8 careers)
  // ==========================================

  {
    name: 'Accounting Intern',
    vietnameseName: 'Thực tập sinh Kế toán',
    description: 'Entry-level internship learning accounting fundamentals and bookkeeping. Assists with accounts payable/receivable, data entry, invoice processing, bank reconciliations, and filing. Excellent foundation for accounting career path.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 65,
        conscientiousness: 85,
        extraversion: 50,
        agreeableness: 75,
        neuroticism: 45,
        eq_emotional_intelligence: 60,
        adaptability: 70,
        stress_tolerance: 60,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 45,
        technical_aptitude: 75,
        communication_written: 65,
        communication_verbal: 60,
        attention_to_detail: 95,
        time_management: 70,
        digital_literacy: 75,
        learning_agility: 85,
        quantitative_analysis: 80,
        financial_modeling: 40,
        risk_assessment: 50,
        regulatory_knowledge: 50,
        business_acumen: 50,
      },
      a3: {
        work_life_balance: 75,
        creativity_vs_structure: 20,
        autonomy_vs_guidance: 25,
        impact_vs_money: 50,
        stability_vs_growth: 80,
        collaboration_vs_solo: 60,
        variety_vs_routine: 40,
      },
    },
    avgSalaryVND: '2,000,000 - 5,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'low',
    growthPotential: 'very_high',
  },

  {
    name: 'Junior Accountant',
    vietnameseName: 'Kế toán Viên',
    description: 'Entry-level accounting role handling day-to-day accounting transactions. Manages accounts payable/receivable, prepares journal entries, assists with month-end close, maintains ledgers, and ensures accuracy in financial records under supervision.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 60,
        conscientiousness: 95,
        extraversion: 45,
        agreeableness: 70,
        neuroticism: 40,
        eq_emotional_intelligence: 60,
        adaptability: 65,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 80,
        creativity: 45,
        technical_aptitude: 80,
        communication_written: 70,
        communication_verbal: 60,
        attention_to_detail: 98,
        time_management: 75,
        digital_literacy: 80,
        learning_agility: 80,
        quantitative_analysis: 85,
        financial_modeling: 50,
        risk_assessment: 55,
        regulatory_knowledge: 65,
        business_acumen: 55,
      },
      a3: {
        work_life_balance: 70,
        creativity_vs_structure: 15,
        autonomy_vs_guidance: 35,
        impact_vs_money: 50,
        stability_vs_growth: 80,
        collaboration_vs_solo: 50,
        variety_vs_routine: 35,
      },
    },
    avgSalaryVND: '7,000,000 - 12,000,000',
    workHoursPerWeek: 42,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Accountant',
    vietnameseName: 'Kế toán Viên Chính',
    description: 'Manages full accounting cycle independently. Prepares financial statements, handles month-end and year-end close, manages tax compliance, conducts reconciliations, and ensures adherence to accounting standards (VAS, IFRS). Core professional accounting role.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 65,
        conscientiousness: 95,
        extraversion: 45,
        agreeableness: 70,
        neuroticism: 35,
        eq_emotional_intelligence: 65,
        adaptability: 70,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 50,
        technical_aptitude: 85,
        communication_written: 75,
        communication_verbal: 65,
        attention_to_detail: 98,
        time_management: 85,
        digital_literacy: 85,
        learning_agility: 75,
        quantitative_analysis: 90,
        financial_modeling: 60,
        risk_assessment: 65,
        regulatory_knowledge: 80,
        business_acumen: 65,
      },
      a3: {
        work_life_balance: 60,
        creativity_vs_structure: 15,
        autonomy_vs_guidance: 55,
        impact_vs_money: 50,
        stability_vs_growth: 75,
        collaboration_vs_solo: 45,
        variety_vs_routine: 35,
      },
    },
    avgSalaryVND: '12,000,000 - 20,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Senior Accountant',
    vietnameseName: 'Kế toán Viên Cấp cao',
    description: 'Leads accounting processes and handles complex accounting issues. Manages financial reporting, coordinates audits, oversees junior accountants, implements accounting policies, analyzes financial data, and ensures compliance with regulations and standards.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 70,
        conscientiousness: 95,
        extraversion: 50,
        agreeableness: 70,
        neuroticism: 30,
        eq_emotional_intelligence: 70,
        adaptability: 75,
        stress_tolerance: 80,
        leadership: 65,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 55,
        technical_aptitude: 90,
        communication_written: 80,
        communication_verbal: 70,
        attention_to_detail: 98,
        time_management: 85,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 90,
        financial_modeling: 70,
        risk_assessment: 75,
        regulatory_knowledge: 90,
        business_acumen: 75,
      },
      a3: {
        work_life_balance: 55,
        creativity_vs_structure: 20,
        autonomy_vs_guidance: 70,
        impact_vs_money: 55,
        stability_vs_growth: 70,
        collaboration_vs_solo: 50,
        variety_vs_routine: 40,
      },
    },
    avgSalaryVND: '20,000,000 - 35,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Accounting Manager',
    vietnameseName: 'Quản lý Kế toán',
    description: 'Manages accounting team and oversees all accounting operations. Leads month-end/year-end close, manages external audits, ensures regulatory compliance, develops accounting procedures, and reports financial results to management.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 70,
        conscientiousness: 98,
        extraversion: 60,
        agreeableness: 75,
        neuroticism: 25,
        eq_emotional_intelligence: 80,
        adaptability: 75,
        stress_tolerance: 85,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 55,
        technical_aptitude: 90,
        communication_written: 85,
        communication_verbal: 80,
        attention_to_detail: 95,
        time_management: 90,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 90,
        financial_modeling: 75,
        risk_assessment: 85,
        regulatory_knowledge: 95,
        business_acumen: 85,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 20,
        autonomy_vs_guidance: 80,
        impact_vs_money: 55,
        stability_vs_growth: 70,
        collaboration_vs_solo: 65,
        variety_vs_routine: 45,
      },
    },
    avgSalaryVND: '35,000,000 - 60,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Financial Controller',
    vietnameseName: 'Giám sát Tài chính',
    description: 'Senior accounting leader overseeing accounting, financial reporting, and controls. Manages accounting and FP&A teams, ensures GAAP/IFRS compliance, leads budgeting and forecasting, coordinates audits, and provides financial insights to CFO and executives.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 98,
        extraversion: 65,
        agreeableness: 70,
        neuroticism: 20,
        eq_emotional_intelligence: 85,
        adaptability: 80,
        stress_tolerance: 90,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 60,
        technical_aptitude: 90,
        communication_written: 90,
        communication_verbal: 85,
        attention_to_detail: 95,
        time_management: 90,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 80,
        risk_assessment: 90,
        regulatory_knowledge: 95,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 25,
        autonomy_vs_guidance: 85,
        impact_vs_money: 60,
        stability_vs_growth: 65,
        collaboration_vs_solo: 65,
        variety_vs_routine: 50,
      },
    },
    avgSalaryVND: '60,000,000 - 100,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Finance Director (Accounting)',
    vietnameseName: 'Giám đốc Tài chính (Kế toán)',
    description: 'Top accounting and finance executive for large organizations. Oversees all accounting, reporting, treasury, and tax functions. Ensures financial integrity, manages external relationships with auditors and regulators, and provides strategic financial leadership.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 98,
        extraversion: 70,
        agreeableness: 70,
        neuroticism: 18,
        eq_emotional_intelligence: 90,
        adaptability: 80,
        stress_tolerance: 95,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 65,
        technical_aptitude: 90,
        communication_written: 90,
        communication_verbal: 90,
        attention_to_detail: 90,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 80,
        risk_assessment: 95,
        regulatory_knowledge: 98,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 25,
        autonomy_vs_guidance: 90,
        impact_vs_money: 60,
        stability_vs_growth: 65,
        collaboration_vs_solo: 65,
        variety_vs_routine: 55,
      },
    },
    avgSalaryVND: '90,000,000 - 140,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  {
    name: 'Chief Accounting Officer',
    vietnameseName: 'Giám đốc Kế toán Cấp cao',
    description: 'C-suite accounting executive for large corporations or public companies. Oversees global accounting operations, ensures financial statement accuracy and regulatory compliance, manages relationships with audit committees and external auditors, and drives accounting excellence.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 100,
        extraversion: 70,
        agreeableness: 70,
        neuroticism: 15,
        eq_emotional_intelligence: 90,
        adaptability: 80,
        stress_tolerance: 95,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 65,
        technical_aptitude: 90,
        communication_written: 95,
        communication_verbal: 95,
        attention_to_detail: 95,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 80,
        risk_assessment: 95,
        regulatory_knowledge: 100,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 25,
        creativity_vs_structure: 20,
        autonomy_vs_guidance: 95,
        impact_vs_money: 60,
        stability_vs_growth: 65,
        collaboration_vs_solo: 60,
        variety_vs_routine: 55,
      },
    },
    avgSalaryVND: '120,000,000 - 200,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ==========================================
  // PHASE 5: BIG 4 TRACK (6 careers)
  // ==========================================

  {
    name: 'Audit/Tax Intern (Big 4)',
    vietnameseName: 'Thực tập sinh Kiểm toán/Thuế (Big 4)',
    description: 'Prestigious internship at Big 4 firms (Deloitte, PwC, KPMG, EY) learning professional audit or tax services. Assists with client engagements, financial statement testing, tax compliance, and documentation. Excellent training and career foundation.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 90,
        extraversion: 65,
        agreeableness: 75,
        neuroticism: 40,
        eq_emotional_intelligence: 70,
        adaptability: 85,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 55,
        technical_aptitude: 80,
        communication_written: 75,
        communication_verbal: 70,
        attention_to_detail: 95,
        time_management: 75,
        digital_literacy: 85,
        learning_agility: 95,
        quantitative_analysis: 85,
        financial_modeling: 55,
        risk_assessment: 65,
        regulatory_knowledge: 65,
        business_acumen: 60,
      },
      a3: {
        work_life_balance: 60,
        creativity_vs_structure: 25,
        autonomy_vs_guidance: 30,
        impact_vs_money: 50,
        stability_vs_growth: 75,
        collaboration_vs_solo: 80,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '3,000,000 - 6,000,000',
    workHoursPerWeek: 42,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'Associate (Big 4 Audit)',
    vietnameseName: 'Chuyên viên Kiểm toán (Big 4)',
    description: 'Entry-level professional at Big 4 firms performing audit procedures, testing financial controls, preparing workpapers, and supporting audit engagements. Works with diverse clients, travels frequently, and learns professional standards. Intense during busy season (50-70 hours/week).',
    category: 'finance',
    requirements: {
      a1: {
        openness: 75,
        conscientiousness: 95,
        extraversion: 70,
        agreeableness: 75,
        neuroticism: 35,
        eq_emotional_intelligence: 75,
        adaptability: 85,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 55,
        technical_aptitude: 85,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 98,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 90,
        quantitative_analysis: 90,
        financial_modeling: 65,
        risk_assessment: 75,
        regulatory_knowledge: 80,
        business_acumen: 70,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 20,
        autonomy_vs_guidance: 40,
        impact_vs_money: 50,
        stability_vs_growth: 70,
        collaboration_vs_solo: 75,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '12,000,000 - 18,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'very_high',
  },

  {
    name: 'Senior Associate (Big 4)',
    vietnameseName: 'Chuyên viên Cấp cao (Big 4)',
    description: 'Leads audit sections and supervises associates. Plans audit procedures, reviews work, coordinates with clients, identifies accounting issues, and manages engagement timelines. Client-facing role requiring strong technical and interpersonal skills.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 75,
        neuroticism: 30,
        eq_emotional_intelligence: 80,
        adaptability: 85,
        stress_tolerance: 85,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 60,
        technical_aptitude: 90,
        communication_written: 85,
        communication_verbal: 85,
        attention_to_detail: 95,
        time_management: 90,
        digital_literacy: 90,
        learning_agility: 80,
        quantitative_analysis: 90,
        financial_modeling: 70,
        risk_assessment: 85,
        regulatory_knowledge: 90,
        business_acumen: 80,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 25,
        autonomy_vs_guidance: 65,
        impact_vs_money: 55,
        stability_vs_growth: 65,
        collaboration_vs_solo: 70,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '20,000,000 - 32,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Manager (Big 4)',
    vietnameseName: 'Quản lý (Big 4)',
    description: 'Manages multiple audit/tax engagements and client relationships. Oversees engagement teams, reviews financial statements, provides technical guidance, develops business, and serves as primary client contact. Critical middle management role with partner track potential.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 85,
        agreeableness: 75,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 90,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 65,
        technical_aptitude: 90,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 90,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 75,
        quantitative_analysis: 90,
        financial_modeling: 75,
        risk_assessment: 90,
        regulatory_knowledge: 95,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 80,
        impact_vs_money: 55,
        stability_vs_growth: 60,
        collaboration_vs_solo: 75,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '40,000,000 - 60,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'very_high',
    growthPotential: 'high',
  },

  {
    name: 'Senior Manager (Big 4)',
    vietnameseName: 'Quản lý Cấp cao (Big 4)',
    description: 'Senior client service professional managing major accounts and complex engagements. Leads large teams, provides expert technical advice, develops new business, mentors managers, and prepares for partnership. High-level client relationships and business development focus.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 90,
        agreeableness: 75,
        neuroticism: 20,
        eq_emotional_intelligence: 95,
        adaptability: 85,
        stress_tolerance: 95,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 70,
        technical_aptitude: 90,
        communication_written: 90,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 70,
        quantitative_analysis: 90,
        financial_modeling: 75,
        risk_assessment: 95,
        regulatory_knowledge: 98,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 25,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 90,
        impact_vs_money: 50,
        stability_vs_growth: 55,
        collaboration_vs_solo: 70,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '65,000,000 - 100,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Partner (Big 4)',
    vietnameseName: 'Đối tác (Big 4)',
    description: 'Equity partner and firm owner responsible for major client relationships, business development, and firm profitability. Owns client portfolio generating millions in fees, makes strategic firm decisions, develops talent, and represents firm in market. Compensation based on firm and individual performance.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 95,
        agreeableness: 75,
        neuroticism: 15,
        eq_emotional_intelligence: 98,
        adaptability: 85,
        stress_tolerance: 98,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 85,
        communication_written: 95,
        communication_verbal: 100,
        attention_to_detail: 80,
        time_management: 95,
        digital_literacy: 80,
        learning_agility: 70,
        quantitative_analysis: 90,
        financial_modeling: 75,
        risk_assessment: 95,
        regulatory_knowledge: 98,
        business_acumen: 100,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 98,
        impact_vs_money: 40,
        stability_vs_growth: 50,
        collaboration_vs_solo: 70,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '150,000,000 - 300,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ==========================================
  // PHASE 6: FINTECH TRACK (5 careers)
  // ==========================================

  {
    name: 'FinTech Intern',
    vietnameseName: 'Thực tập sinh Công nghệ Tài chính',
    description: 'Tech-focused finance internship at FinTech startups or digital banking divisions. Learns about digital payments, blockchain, mobile banking, or financial software. Assists with product development, data analysis, user research, and market analysis.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 75,
        extraversion: 65,
        agreeableness: 75,
        neuroticism: 40,
        eq_emotional_intelligence: 70,
        adaptability: 95,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 85,
        technical_aptitude: 90,
        communication_written: 75,
        communication_verbal: 70,
        attention_to_detail: 80,
        time_management: 70,
        digital_literacy: 95,
        learning_agility: 98,
        quantitative_analysis: 85,
        financial_modeling: 55,
        risk_assessment: 60,
        regulatory_knowledge: 50,
        business_acumen: 65,
      },
      a3: {
        work_life_balance: 65,
        creativity_vs_structure: 75,
        autonomy_vs_guidance: 35,
        impact_vs_money: 60,
        stability_vs_growth: 85,
        collaboration_vs_solo: 75,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '3,000,000 - 7,000,000',
    workHoursPerWeek: 42,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'Junior FinTech Analyst',
    vietnameseName: 'Chuyên viên Phân tích FinTech',
    description: 'Analyzes financial technology trends, digital banking metrics, and payment innovations. Conducts market research, analyzes user behavior, supports product launches, tracks KPIs, and assists in developing FinTech strategies for digital transformation.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 80,
        extraversion: 65,
        agreeableness: 75,
        neuroticism: 35,
        eq_emotional_intelligence: 75,
        adaptability: 95,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 85,
        technical_aptitude: 95,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 85,
        time_management: 80,
        digital_literacy: 98,
        learning_agility: 95,
        quantitative_analysis: 90,
        financial_modeling: 70,
        risk_assessment: 70,
        regulatory_knowledge: 60,
        business_acumen: 75,
      },
      a3: {
        work_life_balance: 55,
        creativity_vs_structure: 75,
        autonomy_vs_guidance: 55,
        impact_vs_money: 60,
        stability_vs_growth: 75,
        collaboration_vs_solo: 70,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '15,000,000 - 25,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'FinTech Product Manager',
    vietnameseName: 'Quản lý Sản phẩm FinTech',
    description: 'Manages development and launch of FinTech products like digital wallets, payment apps, lending platforms, or blockchain solutions. Defines product roadmap, works with engineering teams, conducts user research, analyzes metrics, and drives product-market fit.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 85,
        extraversion: 80,
        agreeableness: 75,
        neuroticism: 30,
        eq_emotional_intelligence: 85,
        adaptability: 95,
        stress_tolerance: 85,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 90,
        technical_aptitude: 95,
        communication_written: 85,
        communication_verbal: 90,
        attention_to_detail: 80,
        time_management: 90,
        digital_literacy: 98,
        learning_agility: 90,
        quantitative_analysis: 85,
        financial_modeling: 75,
        risk_assessment: 80,
        regulatory_knowledge: 75,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 80,
        autonomy_vs_guidance: 75,
        impact_vs_money: 65,
        stability_vs_growth: 65,
        collaboration_vs_solo: 85,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '35,000,000 - 60,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'very_high',
  },

  {
    name: 'Senior FinTech Strategist',
    vietnameseName: 'Chuyên gia Chiến lược FinTech Cấp cao',
    description: 'Develops FinTech strategy and drives digital transformation for financial institutions or FinTech companies. Identifies emerging technologies, evaluates partnerships, designs innovation initiatives, and leads strategic projects in blockchain, AI, digital banking, or payments.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 98,
        conscientiousness: 85,
        extraversion: 80,
        agreeableness: 70,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 98,
        stress_tolerance: 90,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 95,
        technical_aptitude: 95,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 80,
        time_management: 90,
        digital_literacy: 100,
        learning_agility: 95,
        quantitative_analysis: 90,
        financial_modeling: 80,
        risk_assessment: 90,
        regulatory_knowledge: 85,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 85,
        autonomy_vs_guidance: 85,
        impact_vs_money: 70,
        stability_vs_growth: 60,
        collaboration_vs_solo: 75,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '60,000,000 - 100,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Head of FinTech Innovation',
    vietnameseName: 'Trưởng phòng Đổi mới FinTech',
    description: 'Leads FinTech innovation lab or digital transformation for major financial institution. Oversees innovation portfolio, builds partnerships with startups and tech companies, manages investment in emerging technologies, and drives cultural change toward digital-first mindset.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 100,
        conscientiousness: 85,
        extraversion: 85,
        agreeableness: 75,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 98,
        stress_tolerance: 95,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 98,
        technical_aptitude: 95,
        communication_written: 90,
        communication_verbal: 98,
        attention_to_detail: 75,
        time_management: 90,
        digital_literacy: 100,
        learning_agility: 95,
        quantitative_analysis: 90,
        financial_modeling: 80,
        risk_assessment: 90,
        regulatory_knowledge: 85,
        business_acumen: 98,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 90,
        autonomy_vs_guidance: 95,
        impact_vs_money: 75,
        stability_vs_growth: 55,
        collaboration_vs_solo: 80,
        variety_vs_routine: 98,
      },
    },
    avgSalaryVND: '90,000,000 - 150,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  // ==========================================
  // PHASE 7: FINANCIAL ADVISORY/CONSULTING TRACK (6 careers)
  // ==========================================

  {
    name: 'Financial Consulting Intern',
    vietnameseName: 'Thực tập sinh Tư vấn Tài chính',
    description: 'Internship at financial advisory or consulting firms learning client service and business analysis. Supports consulting teams with research, data analysis, presentation preparation, and client deliverables. Exposure to diverse industries and business challenges.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 85,
        extraversion: 70,
        agreeableness: 75,
        neuroticism: 40,
        eq_emotional_intelligence: 75,
        adaptability: 90,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 75,
        technical_aptitude: 80,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 85,
        time_management: 75,
        digital_literacy: 85,
        learning_agility: 95,
        quantitative_analysis: 90,
        financial_modeling: 65,
        risk_assessment: 65,
        regulatory_knowledge: 55,
        business_acumen: 70,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 30,
        impact_vs_money: 55,
        stability_vs_growth: 75,
        collaboration_vs_solo: 80,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '2,500,000 - 6,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'Junior Financial Consultant',
    vietnameseName: 'Tư vấn Tài chính Cơ sở',
    description: 'Entry-level consultant supporting financial advisory projects. Conducts financial analysis, builds models, researches industries, prepares client presentations, and assists with due diligence, valuation, or restructuring engagements. Client-facing with steep learning curve.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 75,
        agreeableness: 70,
        neuroticism: 35,
        eq_emotional_intelligence: 80,
        adaptability: 90,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 85,
        communication_written: 85,
        communication_verbal: 80,
        attention_to_detail: 90,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 90,
        quantitative_analysis: 95,
        financial_modeling: 85,
        risk_assessment: 75,
        regulatory_knowledge: 65,
        business_acumen: 80,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 45,
        impact_vs_money: 50,
        stability_vs_growth: 70,
        collaboration_vs_solo: 75,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '12,000,000 - 22,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'very_high',
  },

  {
    name: 'Financial Consultant',
    vietnameseName: 'Tư vấn Tài chính',
    description: 'Provides financial advisory services to corporate clients on M&A, restructuring, valuations, or strategic finance. Leads analysis workstreams, manages client relationships, develops recommendations, and presents to senior stakeholders. Independent project ownership.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 80,
        agreeableness: 70,
        neuroticism: 30,
        eq_emotional_intelligence: 85,
        adaptability: 90,
        stress_tolerance: 85,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 80,
        technical_aptitude: 90,
        communication_written: 90,
        communication_verbal: 90,
        attention_to_detail: 90,
        time_management: 90,
        digital_literacy: 90,
        learning_agility: 85,
        quantitative_analysis: 95,
        financial_modeling: 95,
        risk_assessment: 85,
        regulatory_knowledge: 75,
        business_acumen: 90,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 65,
        impact_vs_money: 50,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '25,000,000 - 45,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'high',
    growthPotential: 'very_high',
  },

  {
    name: 'Senior Financial Consultant',
    vietnameseName: 'Tư vấn Tài chính Cấp cao',
    description: 'Leads complex financial advisory engagements and manages consulting teams. Develops client strategies, oversees multiple projects, builds C-suite relationships, mentors junior consultants, and drives business development. Subject matter expert in specific advisory areas.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 85,
        agreeableness: 70,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 90,
        stress_tolerance: 90,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 85,
        technical_aptitude: 90,
        communication_written: 95,
        communication_verbal: 95,
        attention_to_detail: 85,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 80,
        quantitative_analysis: 95,
        financial_modeling: 95,
        risk_assessment: 90,
        regulatory_knowledge: 85,
        business_acumen: 95,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 65,
        autonomy_vs_guidance: 80,
        impact_vs_money: 55,
        stability_vs_growth: 55,
        collaboration_vs_solo: 70,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '45,000,000 - 75,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'high',
  },

  {
    name: 'Manager (Financial Advisory)',
    vietnameseName: 'Quản lý Tư vấn Tài chính',
    description: 'Manages financial advisory practice area and multiple client engagements. Leads teams of consultants, manages client relationships at executive level, develops proposals, drives revenue growth, and ensures quality delivery. Bridge between consulting and partnership.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 95,
        extraversion: 90,
        agreeableness: 70,
        neuroticism: 20,
        eq_emotional_intelligence: 95,
        adaptability: 90,
        stress_tolerance: 95,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 85,
        technical_aptitude: 85,
        communication_written: 95,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 75,
        quantitative_analysis: 95,
        financial_modeling: 90,
        risk_assessment: 95,
        regulatory_knowledge: 90,
        business_acumen: 98,
      },
      a3: {
        work_life_balance: 25,
        creativity_vs_structure: 65,
        autonomy_vs_guidance: 90,
        impact_vs_money: 50,
        stability_vs_growth: 50,
        collaboration_vs_solo: 75,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '65,000,000 - 110,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Director (Financial Advisory)',
    vietnameseName: 'Giám đốc Tư vấn Tài chính',
    description: 'Senior leader of financial advisory practice responsible for major client relationships, business development, and practice profitability. Leads marquee engagements, represents firm in market, develops thought leadership, manages P&L, and mentors consulting teams.',
    category: 'finance',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 95,
        extraversion: 95,
        agreeableness: 70,
        neuroticism: 15,
        eq_emotional_intelligence: 98,
        adaptability: 90,
        stress_tolerance: 98,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 85,
        technical_aptitude: 85,
        communication_written: 95,
        communication_verbal: 100,
        attention_to_detail: 80,
        time_management: 95,
        digital_literacy: 80,
        learning_agility: 70,
        quantitative_analysis: 95,
        financial_modeling: 85,
        risk_assessment: 95,
        regulatory_knowledge: 90,
        business_acumen: 100,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 70,
        autonomy_vs_guidance: 95,
        impact_vs_money: 45,
        stability_vs_growth: 45,
        collaboration_vs_solo: 70,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '100,000,000 - 180,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },
];

/**
 * Seed function to populate finance & banking careers
 */
export async function seedFinanceCareers() {
  console.log('💰 Seeding Finance & Banking Careers...\n');

  let createdCount = 0;
  let updatedCount = 0;
  let skippedCount = 0;

  for (const careerData of financeCareers) {
    try {
      const existing = await prisma.career.findUnique({
        where: { name: careerData.name },
      });

      const career = await prisma.career.upsert({
        where: { name: careerData.name },
        update: {
          ...careerData,
        },
        create: {
          ...careerData,
        },
      });

      if (existing) {
        console.log(`   🔄 Updated: ${career.name}`);
        updatedCount++;
      } else {
        console.log(`   ✅ Created: ${career.name}`);
        createdCount++;
      }
    } catch (error: any) {
      console.error(`   ❌ Error seeding ${careerData.name}:`, error.message);
      skippedCount++;
    }
  }

  console.log('\n📊 Finance & Banking Careers Seed Summary:');
  console.log(`   ✅ Created: ${createdCount} careers`);
  console.log(`   🔄 Updated: ${updatedCount} careers`);
  console.log(`   ❌ Skipped: ${skippedCount} careers`);
  console.log(`   📦 Total: ${financeCareers.length} careers\n`);

  return {
    created: createdCount,
    updated: updatedCount,
    skipped: skippedCount,
    total: financeCareers.length,
  };
}

/**
 * Standalone execution
 */
if (require.main === module) {
  seedFinanceCareers()
    .then(() => {
      console.log('✅ Finance careers seed completed successfully!\n');
      process.exit(0);
    })
    .catch((e) => {
      console.error('❌ Seed error:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}

export { financeCareers };
