import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * International Relations Careers Seed Data
 *
 * Coverage:
 * - NGO/Non-Profit Sector (15 careers)
 * - Diplomacy & Government (5 careers)
 * - International Development (8 careers)
 * - Humanitarian & Emergency Response (6 careers)
 * - Policy, Research & Advocacy (8 careers)
 *
 * Total: 42 International Relations careers
 * Experience levels: Intern → Entry → Mid → Senior → Executive
 * Salaries: Realistic Vietnam market rates (2024-2025)
 */

const internationalRelationsCareers = [
  // ============================================
  // PHASE 1: NGO/NON-PROFIT SECTOR (15 careers)
  // ============================================

  // INTERN LEVEL (0-1 years)
  {
    name: 'NGO Intern',
    vietnameseName: 'Thực tập sinh Tổ chức Phi chính phủ',
    description: 'Entry-level internship at non-governmental organizations, learning about international development, project management, community outreach, and NGO operations. Supports program staff with research, data collection, event coordination, and administrative tasks.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 75,
        extraversion: 65,
        agreeableness: 85,
        neuroticism: 40,
        eq_emotional_intelligence: 70,
        adaptability: 85,
        stress_tolerance: 60,
      },
      a2: {
        analytical_thinking: 60,
        creativity: 65,
        technical_aptitude: 55,
        communication_written: 75,
        communication_verbal: 70,
        attention_to_detail: 75,
        time_management: 65,
        digital_literacy: 70,
        learning_agility: 90,
        cross_cultural_competence: 80,
        research_skills: 70,
      },
      a3: {
        work_life_balance: 60,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 30,
        impact_vs_money: 85,
        stability_vs_growth: 75,
        collaboration_vs_solo: 80,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '2,000,000 - 5,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'International Relations Intern',
    vietnameseName: 'Thực tập sinh Quan hệ Quốc tế',
    description: 'Entry-level position supporting international relations activities, including research on global affairs, policy analysis, diplomatic communications, and event coordination for international conferences and meetings.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 75,
        extraversion: 70,
        agreeableness: 80,
        neuroticism: 35,
        eq_emotional_intelligence: 75,
        adaptability: 90,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 60,
        technical_aptitude: 60,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 80,
        time_management: 65,
        digital_literacy: 75,
        learning_agility: 90,
        language_proficiency: 85,
        research_skills: 80,
      },
      a3: {
        work_life_balance: 55,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 25,
        impact_vs_money: 90,
        stability_vs_growth: 80,
        collaboration_vs_solo: 75,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '2,500,000 - 6,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  // ENTRY LEVEL (1-3 years)
  {
    name: 'Program Assistant (NGO)',
    vietnameseName: 'Trợ lý Chương trình (NGO)',
    description: 'Support program implementation at NGOs by coordinating project activities, maintaining databases, preparing reports, liaising with partners, and assisting in monitoring and evaluation. Entry-level role with direct project involvement.',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 80,
        extraversion: 65,
        agreeableness: 85,
        neuroticism: 40,
        eq_emotional_intelligence: 75,
        adaptability: 85,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 70,
        creativity: 60,
        technical_aptitude: 65,
        communication_written: 75,
        communication_verbal: 70,
        attention_to_detail: 85,
        time_management: 75,
        digital_literacy: 75,
        learning_agility: 80,
        project_management: 60,
      },
      a3: {
        work_life_balance: 55,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 40,
        impact_vs_money: 85,
        stability_vs_growth: 70,
        collaboration_vs_solo: 85,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '8,000,000 - 14,000,000',
    workHoursPerWeek: 42,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Project Coordinator (NGO)',
    vietnameseName: 'Điều phối viên Dự án (NGO)',
    description: 'Coordinate day-to-day project activities, manage budgets, organize events and workshops, maintain stakeholder relationships, and ensure project deliverables are met on time. First project management role in NGO sector.',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 85,
        extraversion: 70,
        agreeableness: 85,
        neuroticism: 35,
        eq_emotional_intelligence: 80,
        adaptability: 85,
        stress_tolerance: 70,
        leadership: 60,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 65,
        technical_aptitude: 65,
        communication_written: 80,
        communication_verbal: 75,
        attention_to_detail: 85,
        time_management: 80,
        digital_literacy: 75,
        learning_agility: 75,
        project_management: 75,
        budget_management: 65,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 50,
        impact_vs_money: 85,
        stability_vs_growth: 65,
        collaboration_vs_solo: 85,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '10,000,000 - 18,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'External Relations Officer',
    vietnameseName: 'Chuyên viên Quan hệ Đối ngoại',
    description: 'Manage external communications, build partnerships with stakeholders, coordinate with government agencies and international partners, organize public events, and maintain the organization\'s public image and networks.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 80,
        extraversion: 85,
        agreeableness: 85,
        neuroticism: 30,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 70,
      },
      a2: {
        analytical_thinking: 70,
        creativity: 75,
        technical_aptitude: 65,
        communication_written: 85,
        communication_verbal: 90,
        attention_to_detail: 75,
        time_management: 75,
        digital_literacy: 75,
        learning_agility: 75,
        networking_skills: 90,
        public_speaking: 85,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 55,
        impact_vs_money: 80,
        stability_vs_growth: 65,
        collaboration_vs_solo: 90,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '12,000,000 - 20,000,000',
    workHoursPerWeek: 44,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  // MID-LEVEL (3-7 years)
  {
    name: 'Program Officer (NGO)',
    vietnameseName: 'Chuyên viên Chương trình (NGO)',
    description: 'Lead program implementation, design project proposals, conduct needs assessments, manage budgets, supervise staff, monitor impact, and ensure compliance with donor requirements. Core professional role in NGO program management.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 85,
        extraversion: 70,
        agreeableness: 85,
        neuroticism: 30,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 75,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 80,
        creativity: 70,
        technical_aptitude: 70,
        communication_written: 85,
        communication_verbal: 80,
        attention_to_detail: 85,
        time_management: 80,
        digital_literacy: 75,
        learning_agility: 75,
        project_management: 85,
        strategic_thinking: 75,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 60,
        impact_vs_money: 85,
        stability_vs_growth: 60,
        collaboration_vs_solo: 80,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '18,000,000 - 30,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Project Manager (NGO)',
    vietnameseName: 'Quản lý Dự án (NGO)',
    description: 'Manage entire project lifecycle from design to evaluation, lead teams of 5-15 staff, develop budgets ($100K-$500K), write funding proposals, build partnerships, and report to donors. Senior project leadership role.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 90,
        extraversion: 75,
        agreeableness: 80,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 80,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 75,
        technical_aptitude: 75,
        communication_written: 85,
        communication_verbal: 85,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 70,
        project_management: 90,
        budget_management: 85,
        strategic_thinking: 80,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 70,
        impact_vs_money: 85,
        stability_vs_growth: 55,
        collaboration_vs_solo: 80,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '22,000,000 - 38,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Grants & Partnerships Manager',
    vietnameseName: 'Quản lý Tài trợ & Đối tác',
    description: 'Identify funding opportunities, write grant proposals, manage donor relationships, negotiate partnerships, ensure grant compliance, and develop fundraising strategies. Critical role for NGO sustainability.',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 90,
        extraversion: 80,
        agreeableness: 80,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 80,
        stress_tolerance: 75,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 80,
        technical_aptitude: 70,
        communication_written: 95,
        communication_verbal: 85,
        attention_to_detail: 95,
        time_management: 85,
        digital_literacy: 75,
        learning_agility: 70,
        persuasion_skills: 90,
        financial_management: 85,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 70,
        impact_vs_money: 80,
        stability_vs_growth: 55,
        collaboration_vs_solo: 75,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '20,000,000 - 35,000,000',
    workHoursPerWeek: 46,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  {
    name: 'External Relations Manager',
    vietnameseName: 'Quản lý Quan hệ Đối ngoại',
    description: 'Develop and execute external relations strategy, manage communications team, build high-level partnerships, represent organization at events, handle media relations, and coordinate advocacy campaigns.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 85,
        extraversion: 90,
        agreeableness: 85,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 80,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 80,
        technical_aptitude: 70,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 80,
        time_management: 80,
        digital_literacy: 80,
        learning_agility: 70,
        public_speaking: 95,
        strategic_thinking: 85,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 75,
        impact_vs_money: 75,
        stability_vs_growth: 50,
        collaboration_vs_solo: 85,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '25,000,000 - 42,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Monitoring & Evaluation Manager',
    vietnameseName: 'Quản lý Giám sát & Đánh giá',
    description: 'Design M&E frameworks, develop indicators and tools, conduct evaluations, analyze program impact, train staff on data collection, and produce learning reports for donors and stakeholders.',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 55,
        agreeableness: 75,
        neuroticism: 30,
        eq_emotional_intelligence: 75,
        adaptability: 75,
        stress_tolerance: 75,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 70,
        technical_aptitude: 85,
        communication_written: 85,
        communication_verbal: 75,
        attention_to_detail: 95,
        time_management: 80,
        digital_literacy: 90,
        learning_agility: 75,
        statistical_analysis: 90,
        research_methodology: 90,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 70,
        impact_vs_money: 80,
        stability_vs_growth: 60,
        collaboration_vs_solo: 60,
        variety_vs_routine: 50,
      },
    },
    avgSalaryVND: '22,000,000 - 40,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'medium',
  },

  // SENIOR LEVEL (7-12 years)
  {
    name: 'Senior Program Manager (NGO)',
    vietnameseName: 'Quản lý Chương trình Cấp cao (NGO)',
    description: 'Oversee multiple programs and large portfolios ($1M+), lead program teams of 20-50 staff, develop organizational strategy, manage key donor relationships, and ensure program quality and impact across the organization.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 90,
        extraversion: 75,
        agreeableness: 80,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 85,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 80,
        technical_aptitude: 75,
        communication_written: 90,
        communication_verbal: 90,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 70,
        strategic_thinking: 90,
        people_management: 90,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 85,
        impact_vs_money: 80,
        stability_vs_growth: 50,
        collaboration_vs_solo: 75,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '35,000,000 - 55,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  {
    name: 'Country Director (NGO)',
    vietnameseName: 'Giám đốc Quốc gia (NGO)',
    description: 'Lead all NGO operations in Vietnam, manage budgets of $2M-$10M, oversee 50-200 staff, develop country strategy, represent organization to government and donors, ensure compliance and impact.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 95,
        extraversion: 80,
        agreeableness: 80,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 90,
        stress_tolerance: 90,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 80,
        technical_aptitude: 75,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 70,
        strategic_thinking: 95,
        political_acumen: 90,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 90,
        impact_vs_money: 75,
        stability_vs_growth: 45,
        collaboration_vs_solo: 70,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '50,000,000 - 80,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Head of External Relations',
    vietnameseName: 'Trưởng phòng Quan hệ Đối ngoại',
    description: 'Lead external relations department, develop global communications strategy, manage senior partnerships with governments and UN agencies, oversee advocacy initiatives, and represent organization at high-level forums.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 95,
        agreeableness: 85,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 90,
        stress_tolerance: 85,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 85,
        technical_aptitude: 75,
        communication_written: 95,
        communication_verbal: 98,
        attention_to_detail: 80,
        time_management: 85,
        digital_literacy: 85,
        learning_agility: 75,
        strategic_thinking: 90,
        diplomacy: 95,
      },
      a3: {
        work_life_balance: 25,
        creativity_vs_structure: 65,
        autonomy_vs_guidance: 85,
        impact_vs_money: 75,
        stability_vs_growth: 45,
        collaboration_vs_solo: 80,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '40,000,000 - 65,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  // EXECUTIVE LEVEL (12+ years)
  {
    name: 'Regional Director (NGO)',
    vietnameseName: 'Giám đốc Khu vực (NGO)',
    description: 'Oversee NGO operations across Southeast Asia region, manage budgets of $10M-$50M, lead country directors, develop regional strategy, manage relationships with regional bodies (ASEAN, etc.), ensure organizational growth and impact.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 95,
        extraversion: 85,
        agreeableness: 80,
        neuroticism: 10,
        eq_emotional_intelligence: 98,
        adaptability: 95,
        stress_tolerance: 95,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 85,
        technical_aptitude: 75,
        communication_written: 95,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 90,
        digital_literacy: 80,
        learning_agility: 70,
        strategic_thinking: 98,
        political_acumen: 95,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 95,
        impact_vs_money: 70,
        stability_vs_growth: 40,
        collaboration_vs_solo: 65,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '60,000,000 - 100,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  {
    name: 'Executive Director (NGO)',
    vietnameseName: 'Giám đốc Điều hành (NGO)',
    description: 'Lead entire NGO organization, set strategic vision, manage global operations and budgets ($50M+), engage with boards and major donors, represent organization globally, and ensure organizational sustainability and impact at scale.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 98,
        extraversion: 85,
        agreeableness: 80,
        neuroticism: 10,
        eq_emotional_intelligence: 98,
        adaptability: 95,
        stress_tolerance: 98,
        leadership: 100,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 90,
        technical_aptitude: 75,
        communication_written: 95,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 90,
        digital_literacy: 80,
        learning_agility: 75,
        strategic_thinking: 100,
        visionary_thinking: 98,
      },
      a3: {
        work_life_balance: 10,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 100,
        impact_vs_money: 75,
        stability_vs_growth: 35,
        collaboration_vs_solo: 60,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '70,000,000 - 120,000,000',
    workHoursPerWeek: 60,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  {
    name: 'Communications Director (International)',
    vietnameseName: 'Giám đốc Truyền thông (Quốc tế)',
    description: 'Lead global communications strategy for international organization, manage media relations, oversee digital campaigns, coordinate crisis communications, manage communications team across regions, and protect organizational reputation.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 90,
        agreeableness: 80,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 90,
        stress_tolerance: 90,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 95,
        technical_aptitude: 80,
        communication_written: 98,
        communication_verbal: 98,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 75,
        strategic_thinking: 95,
        crisis_management: 95,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 70,
        autonomy_vs_guidance: 90,
        impact_vs_money: 70,
        stability_vs_growth: 40,
        collaboration_vs_solo: 75,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '55,000,000 - 90,000,000',
    workHoursPerWeek: 52,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // =============================================
  // PHASE 2: DIPLOMACY & GOVERNMENT (5 careers)
  // =============================================

  {
    name: 'Diplomatic Attaché',
    vietnameseName: 'Tùy viên Ngoại giao',
    description: 'Entry-level diplomatic position supporting embassy or consulate operations, handling administrative duties, assisting with diplomatic communications, coordinating events, and supporting visa and consular services.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 90,
        extraversion: 70,
        agreeableness: 85,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 75,
      },
      a2: {
        analytical_thinking: 80,
        creativity: 65,
        technical_aptitude: 70,
        communication_written: 90,
        communication_verbal: 85,
        attention_to_detail: 95,
        time_management: 80,
        digital_literacy: 80,
        learning_agility: 85,
        protocol_knowledge: 85,
        language_proficiency: 95,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 25,
        autonomy_vs_guidance: 45,
        impact_vs_money: 80,
        stability_vs_growth: 70,
        collaboration_vs_solo: 75,
        variety_vs_routine: 65,
      },
    },
    avgSalaryVND: '15,000,000 - 25,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Consular Officer',
    vietnameseName: 'L영사 Consular',
    description: 'Provide consular services to nationals abroad including visa processing, passport services, assistance to citizens in distress, and coordination with local authorities. Front-line diplomatic service role.',
    requirements: {
      a1: {
        openness: 80,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 90,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 85,
        leadership: 65,
      },
      a2: {
        analytical_thinking: 80,
        creativity: 60,
        technical_aptitude: 70,
        communication_written: 85,
        communication_verbal: 90,
        attention_to_detail: 98,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 75,
        crisis_management: 85,
        legal_knowledge: 80,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 20,
        autonomy_vs_guidance: 55,
        impact_vs_money: 85,
        stability_vs_growth: 75,
        collaboration_vs_solo: 70,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '20,000,000 - 35,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  {
    name: 'Political Affairs Officer',
    vietnameseName: 'Chuyên viên Chính trị',
    description: 'Analyze political developments, prepare briefings for ambassadors, monitor government policies, maintain relationships with host government officials, and report on political trends affecting bilateral relations.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 90,
        extraversion: 75,
        agreeableness: 75,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 90,
        stress_tolerance: 85,
        leadership: 70,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 75,
        communication_written: 95,
        communication_verbal: 90,
        attention_to_detail: 90,
        time_management: 80,
        digital_literacy: 85,
        learning_agility: 85,
        geopolitical_analysis: 95,
        research_skills: 95,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 70,
        impact_vs_money: 85,
        stability_vs_growth: 65,
        collaboration_vs_solo: 60,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '25,000,000 - 45,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  {
    name: 'First Secretary (Diplomat)',
    vietnameseName: 'Tham tán Nhất',
    description: 'Senior diplomatic role managing specific portfolio (economic, political, cultural), leading negotiations, representing country at official functions, supervising junior diplomats, and advising ambassador on key issues.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 95,
        extraversion: 85,
        agreeableness: 80,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 95,
        stress_tolerance: 90,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 80,
        technical_aptitude: 75,
        communication_written: 98,
        communication_verbal: 95,
        attention_to_detail: 90,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 80,
        negotiation_skills: 95,
        strategic_thinking: 90,
      },
      a3: {
        work_life_balance: 25,
        creativity_vs_structure: 35,
        autonomy_vs_guidance: 80,
        impact_vs_money: 85,
        stability_vs_growth: 60,
        collaboration_vs_solo: 65,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '40,000,000 - 65,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Ambassador',
    vietnameseName: 'Đại sứ',
    description: 'Represent country at highest diplomatic level, lead embassy operations, conduct high-level negotiations, manage bilateral relations, advise government on foreign policy, and protect national interests abroad.',
    requirements: {
      a1: {
        openness: 98,
        conscientiousness: 98,
        extraversion: 90,
        agreeableness: 85,
        neuroticism: 10,
        eq_emotional_intelligence: 100,
        adaptability: 95,
        stress_tolerance: 95,
        leadership: 100,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 85,
        technical_aptitude: 75,
        communication_written: 100,
        communication_verbal: 100,
        attention_to_detail: 90,
        time_management: 90,
        digital_literacy: 80,
        learning_agility: 80,
        strategic_thinking: 100,
        statecraft: 100,
      },
      a3: {
        work_life_balance: 10,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 95,
        impact_vs_money: 90,
        stability_vs_growth: 50,
        collaboration_vs_solo: 70,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '80,000,000 - 150,000,000',
    workHoursPerWeek: 60,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ========================================================
  // PHASE 3: INTERNATIONAL DEVELOPMENT (8 careers)
  // ========================================================

  {
    name: 'Development Intern',
    vietnameseName: 'Thực tập sinh Phát triển Quốc tế',
    description: 'Support international development projects focused on poverty reduction, education, health, or economic development. Assist with research, data collection, community surveys, and program documentation.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 75,
        extraversion: 65,
        agreeableness: 90,
        neuroticism: 40,
        eq_emotional_intelligence: 75,
        adaptability: 90,
        stress_tolerance: 60,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 70,
        technical_aptitude: 60,
        communication_written: 75,
        communication_verbal: 70,
        attention_to_detail: 80,
        time_management: 65,
        digital_literacy: 75,
        learning_agility: 95,
        cross_cultural_competence: 85,
      },
      a3: {
        work_life_balance: 60,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 30,
        impact_vs_money: 95,
        stability_vs_growth: 80,
        collaboration_vs_solo: 85,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '2,500,000 - 6,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'medium',
    growthPotential: 'very_high',
  },

  {
    name: 'Development Officer',
    vietnameseName: 'Chuyên viên Phát triển',
    description: 'Implement development programs in areas like education, health, microfinance, or agriculture. Work with communities, conduct assessments, deliver training, monitor progress, and report to donors.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 85,
        extraversion: 70,
        agreeableness: 90,
        neuroticism: 30,
        eq_emotional_intelligence: 85,
        adaptability: 90,
        stress_tolerance: 75,
        leadership: 70,
      },
      a2: {
        analytical_thinking: 80,
        creativity: 75,
        technical_aptitude: 70,
        communication_written: 80,
        communication_verbal: 85,
        attention_to_detail: 85,
        time_management: 80,
        digital_literacy: 75,
        learning_agility: 80,
        community_engagement: 90,
        technical_expertise: 75,
      },
      a3: {
        work_life_balance: 45,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 60,
        impact_vs_money: 95,
        stability_vs_growth: 65,
        collaboration_vs_solo: 90,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '15,000,000 - 28,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Development Program Manager',
    vietnameseName: 'Quản lý Chương trình Phát triển',
    description: 'Manage development programs addressing SDGs, lead project teams, develop theories of change, coordinate with government and local partners, manage budgets, and ensure sustainable impact.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 75,
        agreeableness: 85,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 90,
        stress_tolerance: 80,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 80,
        technical_aptitude: 75,
        communication_written: 85,
        communication_verbal: 85,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 75,
        project_management: 90,
        systems_thinking: 85,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 75,
        impact_vs_money: 90,
        stability_vs_growth: 55,
        collaboration_vs_solo: 85,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '28,000,000 - 48,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'high',
  },

  {
    name: 'Technical Advisor (Development)',
    vietnameseName: 'Cố vấn Kỹ thuật (Phát triển)',
    description: 'Provide specialized technical expertise (health, education, WASH, governance) to development programs, conduct capacity building, design technical interventions, and advise government counterparts.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 65,
        agreeableness: 85,
        neuroticism: 25,
        eq_emotional_intelligence: 85,
        adaptability: 90,
        stress_tolerance: 80,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 80,
        technical_aptitude: 95,
        communication_written: 85,
        communication_verbal: 85,
        attention_to_detail: 90,
        time_management: 80,
        digital_literacy: 85,
        learning_agility: 80,
        subject_matter_expertise: 98,
        training_skills: 90,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 45,
        autonomy_vs_guidance: 80,
        impact_vs_money: 90,
        stability_vs_growth: 60,
        collaboration_vs_solo: 70,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '35,000,000 - 60,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'medium',
    growthPotential: 'medium',
  },

  {
    name: 'UN Programme Officer (JPO)',
    vietnameseName: 'Chuyên viên Chương trình LHQ (JPO)',
    description: 'Junior Professional Officer working for UN agencies (UNDP, UNICEF, WHO, etc.), supporting program design and implementation, conducting research, coordinating with governments, and contributing to global development goals.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 90,
        extraversion: 70,
        agreeableness: 85,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 95,
        stress_tolerance: 80,
        leadership: 70,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 75,
        technical_aptitude: 80,
        communication_written: 95,
        communication_verbal: 85,
        attention_to_detail: 90,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 90,
        policy_analysis: 90,
        multilateral_diplomacy: 85,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 65,
        impact_vs_money: 95,
        stability_vs_growth: 70,
        collaboration_vs_solo: 80,
        variety_vs_routine: 85,
      },
    },
    avgSalaryVND: '30,000,000 - 55,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'UN Programme Specialist',
    vietnameseName: 'Chuyên gia Chương trình LHQ',
    description: 'Mid-to-senior level UN position leading programs in specific sectors, managing portfolios, coordinating with government ministries, mobilizing resources, and representing UN agency at technical meetings.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 85,
        neuroticism: 20,
        eq_emotional_intelligence: 95,
        adaptability: 95,
        stress_tolerance: 85,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 80,
        technical_aptitude: 85,
        communication_written: 95,
        communication_verbal: 90,
        attention_to_detail: 90,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 80,
        strategic_thinking: 90,
        policy_expertise: 95,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 80,
        impact_vs_money: 90,
        stability_vs_growth: 65,
        collaboration_vs_solo: 75,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '50,000,000 - 85,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  {
    name: 'UN Country Director',
    vietnameseName: 'Giám đốc Quốc gia LHQ',
    description: 'Lead UN agency operations in Vietnam, oversee country programs and budgets ($10M-$100M), coordinate with government at ministerial level, represent agency to donors, and ensure achievement of development outcomes.',
    requirements: {
      a1: {
        openness: 98,
        conscientiousness: 98,
        extraversion: 85,
        agreeableness: 85,
        neuroticism: 15,
        eq_emotional_intelligence: 98,
        adaptability: 95,
        stress_tolerance: 95,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 85,
        technical_aptitude: 80,
        communication_written: 98,
        communication_verbal: 98,
        attention_to_detail: 90,
        time_management: 90,
        digital_literacy: 85,
        learning_agility: 75,
        strategic_thinking: 98,
        political_acumen: 98,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 95,
        impact_vs_money: 85,
        stability_vs_growth: 55,
        collaboration_vs_solo: 70,
        variety_vs_routine: 80,
      },
    },
    avgSalaryVND: '90,000,000 - 150,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  {
    name: 'Chief of Development Cooperation',
    vietnameseName: 'Trưởng Ban Hợp tác Phát triển',
    description: 'Lead development cooperation unit in government ministry, coordinate with international donors and development partners, manage ODA portfolio, negotiate agreements, and align international aid with national priorities.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 98,
        extraversion: 75,
        agreeableness: 80,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 85,
        stress_tolerance: 85,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 75,
        technical_aptitude: 80,
        communication_written: 90,
        communication_verbal: 90,
        attention_to_detail: 95,
        time_management: 85,
        digital_literacy: 80,
        learning_agility: 70,
        negotiation_skills: 95,
        policy_knowledge: 95,
      },
      a3: {
        work_life_balance: 30,
        creativity_vs_structure: 30,
        autonomy_vs_guidance: 85,
        impact_vs_money: 80,
        stability_vs_growth: 70,
        collaboration_vs_solo: 75,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '45,000,000 - 75,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'low',
  },

  // ================================================================
  // PHASE 4: HUMANITARIAN & EMERGENCY RESPONSE (6 careers)
  // ================================================================

  {
    name: 'Humanitarian Affairs Intern',
    vietnameseName: 'Thực tập sinh Nhân đạo',
    description: 'Support humanitarian response operations during emergencies and disasters, assist with needs assessments, coordinate relief supplies, support beneficiary registration, and help with reporting to humanitarian clusters.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 80,
        extraversion: 70,
        agreeableness: 95,
        neuroticism: 35,
        eq_emotional_intelligence: 80,
        adaptability: 95,
        stress_tolerance: 70,
      },
      a2: {
        analytical_thinking: 70,
        creativity: 75,
        technical_aptitude: 65,
        communication_written: 75,
        communication_verbal: 75,
        attention_to_detail: 85,
        time_management: 75,
        digital_literacy: 75,
        learning_agility: 95,
        crisis_response: 75,
        resilience: 80,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 35,
        impact_vs_money: 100,
        stability_vs_growth: 70,
        collaboration_vs_solo: 90,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '3,000,000 - 7,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'high',
    growthPotential: 'very_high',
  },

  {
    name: 'Field Officer (Humanitarian)',
    vietnameseName: 'Cán bộ Hiện trường (Nhân đạo)',
    description: 'Work in disaster-affected areas delivering humanitarian assistance, conducting rapid assessments, coordinating with local authorities and communities, managing distribution of relief items, and ensuring accountability.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 85,
        extraversion: 75,
        agreeableness: 90,
        neuroticism: 25,
        eq_emotional_intelligence: 90,
        adaptability: 98,
        stress_tolerance: 85,
        leadership: 70,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 80,
        technical_aptitude: 70,
        communication_written: 75,
        communication_verbal: 85,
        attention_to_detail: 85,
        time_management: 85,
        digital_literacy: 70,
        learning_agility: 85,
        crisis_management: 90,
        problem_solving: 90,
      },
      a3: {
        work_life_balance: 20,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 70,
        impact_vs_money: 100,
        stability_vs_growth: 50,
        collaboration_vs_solo: 85,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '12,000,000 - 22,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'very_high',
    growthPotential: 'high',
  },

  {
    name: 'Emergency Response Coordinator',
    vietnameseName: 'Điều phối viên Ứng phó Khẩn cấp',
    description: 'Coordinate emergency response operations during disasters, lead rapid response teams, manage emergency supplies and logistics, coordinate with humanitarian clusters, activate contingency plans, and report to donors.',
    requirements: {
      a1: {
        openness: 85,
        conscientiousness: 95,
        extraversion: 80,
        agreeableness: 85,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 98,
        stress_tolerance: 95,
        leadership: 90,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 85,
        technical_aptitude: 80,
        communication_written: 85,
        communication_verbal: 90,
        attention_to_detail: 90,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 80,
        crisis_management: 98,
        decision_making: 95,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 80,
        impact_vs_money: 100,
        stability_vs_growth: 40,
        collaboration_vs_solo: 90,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '25,000,000 - 45,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Humanitarian Program Manager',
    vietnameseName: 'Quản lý Chương trình Nhân đạo',
    description: 'Manage humanitarian programs addressing protection, WASH, shelter, food security, or health needs. Lead emergency assessments, design interventions, manage teams in challenging environments, ensure humanitarian principles.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 90,
        extraversion: 75,
        agreeableness: 90,
        neuroticism: 20,
        eq_emotional_intelligence: 95,
        adaptability: 98,
        stress_tolerance: 90,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 80,
        technical_aptitude: 80,
        communication_written: 85,
        communication_verbal: 90,
        attention_to_detail: 85,
        time_management: 90,
        digital_literacy: 80,
        learning_agility: 80,
        humanitarian_standards: 95,
        security_management: 90,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 85,
        impact_vs_money: 100,
        stability_vs_growth: 35,
        collaboration_vs_solo: 85,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '30,000,000 - 55,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'high',
  },

  {
    name: 'Head of Humanitarian Operations',
    vietnameseName: 'Trưởng phòng Hoạt động Nhân đạo',
    description: 'Lead humanitarian operations for organization in emergency contexts, manage multiple humanitarian programs, oversee security and safety, coordinate with UN OCHA and clusters, ensure compliance with humanitarian standards.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 95,
        extraversion: 80,
        agreeableness: 85,
        neuroticism: 15,
        eq_emotional_intelligence: 98,
        adaptability: 98,
        stress_tolerance: 98,
        leadership: 98,
      },
      a2: {
        analytical_thinking: 95,
        creativity: 85,
        technical_aptitude: 85,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 90,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 75,
        strategic_thinking: 95,
        crisis_leadership: 100,
      },
      a3: {
        work_life_balance: 10,
        creativity_vs_structure: 55,
        autonomy_vs_guidance: 90,
        impact_vs_money: 100,
        stability_vs_growth: 30,
        collaboration_vs_solo: 80,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '50,000,000 - 85,000,000',
    workHoursPerWeek: 60,
    stressLevel: 'very_high',
    growthPotential: 'medium',
  },

  {
    name: 'Humanitarian Coordinator',
    vietnameseName: 'Điều phối viên Nhân đạo (HC)',
    description: 'UN-appointed senior role leading humanitarian response in crisis-affected countries, coordinate all UN agencies and NGOs, chair humanitarian country team, mobilize resources, advocate for humanitarian access and protection.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 98,
        extraversion: 85,
        agreeableness: 90,
        neuroticism: 10,
        eq_emotional_intelligence: 100,
        adaptability: 100,
        stress_tolerance: 100,
        leadership: 100,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 90,
        technical_aptitude: 85,
        communication_written: 98,
        communication_verbal: 100,
        attention_to_detail: 90,
        time_management: 95,
        digital_literacy: 85,
        learning_agility: 80,
        strategic_thinking: 100,
        humanitarian_diplomacy: 100,
      },
      a3: {
        work_life_balance: 5,
        creativity_vs_structure: 60,
        autonomy_vs_guidance: 100,
        impact_vs_money: 100,
        stability_vs_growth: 25,
        collaboration_vs_solo: 85,
        variety_vs_routine: 100,
      },
    },
    avgSalaryVND: '120,000,000 - 200,000,000',
    workHoursPerWeek: 65,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },

  // ============================================================
  // PHASE 5: POLICY, RESEARCH & ADVOCACY (8 careers)
  // ============================================================

  {
    name: 'Policy Research Intern',
    vietnameseName: 'Thực tập sinh Nghiên cứu Chính sách',
    description: 'Support policy research on international issues, assist with literature reviews, collect and analyze data, prepare research summaries, and contribute to policy briefs and reports for think tanks or research institutes.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 85,
        extraversion: 50,
        agreeableness: 70,
        neuroticism: 35,
        eq_emotional_intelligence: 70,
        adaptability: 80,
        stress_tolerance: 65,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 75,
        technical_aptitude: 75,
        communication_written: 85,
        communication_verbal: 65,
        attention_to_detail: 95,
        time_management: 70,
        digital_literacy: 85,
        learning_agility: 95,
        research_methodology: 85,
        critical_thinking: 90,
      },
      a3: {
        work_life_balance: 65,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 40,
        impact_vs_money: 85,
        stability_vs_growth: 75,
        collaboration_vs_solo: 50,
        variety_vs_routine: 60,
      },
    },
    avgSalaryVND: '2,500,000 - 6,000,000',
    workHoursPerWeek: 40,
    stressLevel: 'low',
    growthPotential: 'high',
  },

  {
    name: 'Policy Analyst (International)',
    vietnameseName: 'Chuyên viên Phân tích Chính sách (Quốc tế)',
    description: 'Analyze international policies and trends, conduct research on global issues (trade, climate, security), prepare policy briefs, provide recommendations to decision-makers, and contribute to policy debates.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 90,
        extraversion: 60,
        agreeableness: 70,
        neuroticism: 25,
        eq_emotional_intelligence: 75,
        adaptability: 85,
        stress_tolerance: 75,
        leadership: 60,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 80,
        technical_aptitude: 80,
        communication_written: 95,
        communication_verbal: 75,
        attention_to_detail: 95,
        time_management: 80,
        digital_literacy: 90,
        learning_agility: 90,
        policy_analysis: 95,
        quantitative_skills: 85,
      },
      a3: {
        work_life_balance: 55,
        creativity_vs_structure: 40,
        autonomy_vs_guidance: 70,
        impact_vs_money: 85,
        stability_vs_growth: 70,
        collaboration_vs_solo: 50,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '15,000,000 - 30,000,000',
    workHoursPerWeek: 42,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Advocacy Officer',
    vietnameseName: 'Chuyên viên Vận động Chính sách',
    description: 'Lead advocacy campaigns on international issues (human rights, environment, development), coordinate coalitions, engage with policymakers, organize public events, use media and social media for advocacy.',
    requirements: {
      a1: {
        openness: 90,
        conscientiousness: 80,
        extraversion: 85,
        agreeableness: 80,
        neuroticism: 30,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 75,
        leadership: 75,
      },
      a2: {
        analytical_thinking: 75,
        creativity: 90,
        technical_aptitude: 70,
        communication_written: 90,
        communication_verbal: 95,
        attention_to_detail: 75,
        time_management: 80,
        digital_literacy: 90,
        learning_agility: 80,
        campaigning_skills: 95,
        persuasion_skills: 95,
      },
      a3: {
        work_life_balance: 40,
        creativity_vs_structure: 75,
        autonomy_vs_guidance: 70,
        impact_vs_money: 95,
        stability_vs_growth: 55,
        collaboration_vs_solo: 85,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '16,000,000 - 32,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'high',
  },

  {
    name: 'Senior Policy Advisor',
    vietnameseName: 'Cố vấn Chính sách Cấp cao',
    description: 'Advise senior leadership and government officials on international policy issues, lead policy research initiatives, represent organization in policy forums, build coalitions, and influence policy decisions.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 75,
        neuroticism: 20,
        eq_emotional_intelligence: 90,
        adaptability: 90,
        stress_tolerance: 85,
        leadership: 85,
      },
      a2: {
        analytical_thinking: 98,
        creativity: 85,
        technical_aptitude: 80,
        communication_written: 98,
        communication_verbal: 95,
        attention_to_detail: 90,
        time_management: 85,
        digital_literacy: 85,
        learning_agility: 80,
        strategic_thinking: 98,
        policy_expertise: 98,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 50,
        autonomy_vs_guidance: 85,
        impact_vs_money: 85,
        stability_vs_growth: 60,
        collaboration_vs_solo: 65,
        variety_vs_routine: 75,
      },
    },
    avgSalaryVND: '40,000,000 - 70,000,000',
    workHoursPerWeek: 48,
    stressLevel: 'high',
    growthPotential: 'medium',
  },

  {
    name: 'Advocacy Director',
    vietnameseName: 'Giám đốc Vận động Chính sách',
    description: 'Lead advocacy department and strategy, manage campaigns on major global issues, coordinate with international advocacy networks, represent organization to governments and multilateral bodies, mobilize public support.',
    requirements: {
      a1: {
        openness: 95,
        conscientiousness: 90,
        extraversion: 90,
        agreeableness: 80,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 90,
        stress_tolerance: 90,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 85,
        creativity: 95,
        technical_aptitude: 75,
        communication_written: 98,
        communication_verbal: 100,
        attention_to_detail: 80,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 75,
        strategic_thinking: 95,
        political_strategy: 98,
      },
      a3: {
        work_life_balance: 25,
        creativity_vs_structure: 75,
        autonomy_vs_guidance: 90,
        impact_vs_money: 90,
        stability_vs_growth: 45,
        collaboration_vs_solo: 80,
        variety_vs_routine: 90,
      },
    },
    avgSalaryVND: '50,000,000 - 85,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'high',
    growthPotential: 'low',
  },

  {
    name: 'Think Tank Research Fellow',
    vietnameseName: 'Nghiên cứu viên Viện Nghiên cứu',
    description: 'Conduct independent research on international relations and global policy issues, publish in academic and policy journals, present at conferences, advise governments and international organizations, contribute to public debate.',
    requirements: {
      a1: {
        openness: 100,
        conscientiousness: 95,
        extraversion: 65,
        agreeableness: 70,
        neuroticism: 25,
        eq_emotional_intelligence: 75,
        adaptability: 85,
        stress_tolerance: 75,
        leadership: 70,
      },
      a2: {
        analytical_thinking: 100,
        creativity: 90,
        technical_aptitude: 85,
        communication_written: 100,
        communication_verbal: 85,
        attention_to_detail: 98,
        time_management: 80,
        digital_literacy: 90,
        learning_agility: 95,
        research_methodology: 100,
        academic_writing: 100,
      },
      a3: {
        work_life_balance: 50,
        creativity_vs_structure: 80,
        autonomy_vs_guidance: 95,
        impact_vs_money: 80,
        stability_vs_growth: 60,
        collaboration_vs_solo: 30,
        variety_vs_routine: 60,
      },
    },
    avgSalaryVND: '35,000,000 - 65,000,000',
    workHoursPerWeek: 45,
    stressLevel: 'medium',
    growthPotential: 'medium',
  },

  {
    name: 'Director of Research (Think Tank)',
    vietnameseName: 'Giám đốc Nghiên cứu (Viện Nghiên cứu)',
    description: 'Lead research agenda for think tank or policy institute, manage research teams, secure funding for research projects, build partnerships with universities and policymakers, publish influential research, shape policy debates.',
    requirements: {
      a1: {
        openness: 100,
        conscientiousness: 95,
        extraversion: 75,
        agreeableness: 75,
        neuroticism: 20,
        eq_emotional_intelligence: 85,
        adaptability: 85,
        stress_tolerance: 85,
        leadership: 95,
      },
      a2: {
        analytical_thinking: 100,
        creativity: 95,
        technical_aptitude: 85,
        communication_written: 100,
        communication_verbal: 95,
        attention_to_detail: 90,
        time_management: 85,
        digital_literacy: 90,
        learning_agility: 85,
        strategic_thinking: 98,
        thought_leadership: 100,
      },
      a3: {
        work_life_balance: 35,
        creativity_vs_structure: 75,
        autonomy_vs_guidance: 95,
        impact_vs_money: 80,
        stability_vs_growth: 55,
        collaboration_vs_solo: 60,
        variety_vs_routine: 70,
      },
    },
    avgSalaryVND: '60,000,000 - 100,000,000',
    workHoursPerWeek: 50,
    stressLevel: 'medium',
    growthPotential: 'low',
  },

  {
    name: 'Global Campaigns Director',
    vietnameseName: 'Giám đốc Chiến dịch Toàn cầu',
    description: 'Lead global advocacy and campaigning for international NGO on major issues (climate, human rights, poverty), coordinate campaigns across regions, mobilize millions of supporters, engage with UN and governments, drive systemic change.',
    requirements: {
      a1: {
        openness: 98,
        conscientiousness: 90,
        extraversion: 95,
        agreeableness: 80,
        neuroticism: 15,
        eq_emotional_intelligence: 95,
        adaptability: 95,
        stress_tolerance: 95,
        leadership: 100,
      },
      a2: {
        analytical_thinking: 90,
        creativity: 100,
        technical_aptitude: 80,
        communication_written: 98,
        communication_verbal: 100,
        attention_to_detail: 80,
        time_management: 90,
        digital_literacy: 95,
        learning_agility: 80,
        strategic_thinking: 100,
        movement_building: 100,
      },
      a3: {
        work_life_balance: 15,
        creativity_vs_structure: 85,
        autonomy_vs_guidance: 95,
        impact_vs_money: 100,
        stability_vs_growth: 40,
        collaboration_vs_solo: 85,
        variety_vs_routine: 95,
      },
    },
    avgSalaryVND: '70,000,000 - 120,000,000',
    workHoursPerWeek: 55,
    stressLevel: 'very_high',
    growthPotential: 'low',
  },
];

export async function seedInternationalRelationsCareers() {
  console.log('🌱 Starting international relations careers seed...\n');

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const careerData of internationalRelationsCareers) {
    try {
      const existing = await prisma.career.findUnique({
        where: { name: careerData.name },
      });

      const career = await prisma.career.upsert({
        where: { name: careerData.name },
        update: {
          ...careerData,
        },
        create: {
          ...careerData,
        },
      });

      if (existing) {
        console.log(`✅ Updated: ${career.name}`);
        updated++;
      } else {
        console.log(`✨ Created: ${career.name}`);
        created++;
      }
    } catch (error: any) {
      console.error(`❌ Error seeding ${careerData.name}:`, error.message);
      skipped++;
    }
  }

  console.log('\n📊 International Relations Careers Seed Summary:');
  console.log(`   ✨ Created: ${created}`);
  console.log(`   ✅ Updated: ${updated}`);
  console.log(`   ❌ Skipped: ${skipped}`);
  console.log(`   📦 Total: ${internationalRelationsCareers.length}\n`);

  return {
    created,
    updated,
    skipped,
    total: internationalRelationsCareers.length,
  };
}

// Run seed if executed directly
if (require.main === module) {
  seedInternationalRelationsCareers()
    .then(() => {
      console.log('✅ Seed completed successfully!\n');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Seed failed:', error);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
